language: node_js
dist: xenial
node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - "npm config set strict-ssl false"
  - "./misc/node_version.sh"
  - "npm install -g mocha@2.x voc"
  - "npm install blanket"
  - "npm install word crc-32"
  - "npm install coveralls mocha-lcov-reporter"
before_script:
  - "make init"
install:
  - npm install
after_success:
  - "make coveralls-spin"
